# Generated by Django 4.1.1 on 2022-09-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_messages_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
