# Generated by Django 4.1.1 on 2022-09-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_friend_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='my_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
