# Generated by Django 4.1.1 on 2022-09-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_message_my_content_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='userchat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
