# Generated by Django 4.1.1 on 2022-09-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_conversation_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='profile',
        ),
        migrations.AddField(
            model_name='conversation',
            name='userchat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
