# Generated by Django 4.1.1 on 2022-09-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_nick_name_comment_nickname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='mycontent',
        ),
    ]
