# Generated by Django 4.1.1 on 2022-09-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_rename_content_message_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
