# Generated by Django 4.1.1 on 2022-09-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_conversation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='my_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
