# Generated by Django 4.1.1 on 2022-09-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_message_my_message_alter_conversation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile_comment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
