# Generated by Django 4.1.1 on 2022-09-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_comment_profile_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='avatar_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='avatar_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
