# Generated by Django 4.1.1 on 2022-09-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_like_comment_alter_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
